"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['BombiCookies.py']
DATA_FILES = ["cookie2.png", "cookie_icon.png", "milk.png", "splash.png"]
OPTIONS = {
    'iconfile': 'cookie_icon.png'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)